controllers:
    resource: ../src/Controller/
    type: attribute


app_infoEnvoie:
    path: '/infoEnvoie'
    controller: App\Controller\InfoEnvoieController::index

traitement_formulaire:
    path: '/traitement-formulaire'
    controller: App\Controller\InfoEnvoieController::traitementFormulaire

choisir_relais:
    path: '/choisir-relais'
    controller: App\Controller\ChoisirRelaisController::index

// nezofhazoihtiouqzehtsuoghseriuodgtfiuzqgsertiuehydfu